batch_size: 1
epoch: 20
learning_rate: 1e-3
gpu: 1
num_point: 5024
optimizer: Adam
weight_decay: 1e-4
normal: True
lr_decay: 0.5
step_size: 20

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/eyeseg/${model.name}

  sweep:
    dir: log/eyeseg
    subdir: ${model.name}